CREATE TABLE Images(
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  width SMALLINT(4) NOT NULL,
  height SMALLINT(4) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE PicturesType(
  id SMALLINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  caption VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
);

INSERT INTO PicturesType(id, caption) VALUES
  (1, '2D Pictures'),
  (2, '3D Art');

CREATE TABLE Pictures(
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  typeId SMALLINT(2) UNSIGNED NOT NULL,
  title VARCHAR(500) NOT NULL,
  description TEXT NULL DEFAULT NULL,
  smallThumbId INT(10) UNSIGNED NULL DEFAULT NULL,
  bigThumbId INT(10) UNSIGNED NULL DEFAULT NULL,
  srcId INT(10) UNSIGNED NULL DEFAULT NULL,
  coverId INT(10) UNSIGNED NULL DEFAULT NULL,
  facadeIndex SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX Pictures_ixTypeId(typeId),
  CONSTRAINT Pictures_ctTypeId FOREIGN KEY Pictures_fkTypeId(typeId) REFERENCES PicturesType(id) ON UPDATE CASCADE ON DELETE CASCADE,
  PRIMARY KEY(id)
);

CREATE TABLE Videos(
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  ytId VARCHAR(50) NOT NULL,
  title VARCHAR(500) NOT NULL,
  description TEXT NULL DEFAULT NULL,
  smallThumbId INT(10) UNSIGNED NULL DEFAULT NULL,
  bigThumbId INT(10) UNSIGNED NULL DEFAULT NULL,
  coverId INT(10) UNSIGNED NULL DEFAULT NULL,
  facadeIndex SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);