CREATE DATABASE dx_portfolio;

USE dx_portfolio;

CREATE TABLE pictures_type(
  id SMALLINT(2) UNSIGNED NOT NULL AUTO_INCREMENT,
  caption VARCHAR(255) NOT NULL,
  PRIMARY KEY(id)
);

INSERT INTO pictures_type(id, caption) VALUES
  (1, '2D Pictures'),
  (2, '3D Art');

CREATE TABLE videos(
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(500) NOT NULL,
  description TEXT NULL DEFAULT NULL,
  thumb_small INT(10) UNSIGNED NULL DEFAULT NULL,
  thumb_big INT(10) UNSIGNED NULL DEFAULT NULL,
  youtube_id VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE pictures(
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  type_id SMALLINT(2) UNSIGNED NOT NULL,
  title VARCHAR(500) NOT NULL,
  description TEXT NULL DEFAULT NULL,
  thumb_small INT(10) UNSIGNED NULL DEFAULT NULL,
  thumb_big INT(10) UNSIGNED NULL DEFAULT NULL,
  src INT(10) UNSIGNED NULL DEFAULT NULL,
  INDEX inx_type_id(type_id),
  CONSTRAINT ct_type_id FOREIGN KEY fk_type_id(type_id) REFERENCES pictures_type(id) ON UPDATE CASCADE ON DELETE CASCADE,
  PRIMARY KEY(id)
);

CREATE TABLE images(
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  width SMALLINT(4) NOT NULL,
  height SMALLINT(4) NOT NULL,
  PRIMARY KEY(id)
);